### ISSUE TITLE
기업정보 페이지 CSS 최종 수정

### ISSUE THREAD

**Issue by govl7016** [S0Log/SOLog-FE#116]
## Description

- 기업 분석 페이지 CSS 최종 수정

## Todo

- [x] 기업 분석 페이지1 컴포넌트 간격 수정 테스트
- [x] 기업개요 부분 데이터 많이 넘어노는 것 4개로 잘라서 렌더링 
- [x] 매출 비중 추이 차트 레전드 삭제
- [x] 매출 비중 추이 테이블 수정
- [x] 시장 점유율 차트 그리드 맞게 수정(부모 컴포넌트의 높이에 맞춰서)
- [x] 경쟁사 비교 상단 margin, padding 값 일정하게 맞추기
- [x] 차트 Values 내용 설정
- [x] Search useContext 수정
- [x] 기업상세 테이블 단위 수정
- [x] 과거비교 페이지 캘린더 선택하면 전날로 선택되는 것 수정
- [x] 차트 x축 기울어지는 거 수평 가능 여부 확인
