### ISSUE TITLE
Search.jsx 초성 검색 기능 구현

### ISSUE THREAD

**Issue by govl7016** [S0Log/SOLog-FE#18]
## Description

- Search.jsx 초성으로 검색했을 때도 해당 초성이 포함된 기업명이 뜨는 기능 구현

## Todo

- [ ] 토스 초성 검색 라이브러리 es-hangul 활용
- [ ] 강사님께서 알려주신 swr 라이브러리 사용해보기
- [ ] 기능 구현 후 의존성으로 인해 속도 느려지지 않는 지 확인
